[package]
name = "tokio-one-serial"
version = "0.1.0"
authors = ["jadamcrain <jadamcrain@gmail.com>"]
edition = "2018"

[dependencies]
serialport = "4.0"
tokio = { version = "1.0", features=["net"] }
